### ISSUE TITLE
remove() does not trigger namespaced events

### ISSUE THREAD

**Issue by Gamadril** [hay/stapes#49]
Test case:
```
var Module = Stapes.subclass();
var module = new Module();

module.on({
    'change:fruit': function (value) {
        console.log('fruit changed: ' + value);
    }
});
module.set('fruit', 'ORANGE');
module.remove();
```
generic change and remove events are triggered as documented, but namespaced events not.

**Comment by foxx** [comment]
@Gamadril @supermensa Could you confirm whether or not this issue is a bug or not? Based on the reply from @bitinn it seems like more of a feature request afaik.
