### ISSUE TITLE
Missing comma in introduction code

### ISSUE THREAD

**Issue by supermensa** [hay/stapes#59]
```
var Module = Stapes.subclass({
    constructor : function(name) {
        this.name = name;
    }

// missing comma here ,

    sayName : function() {
        console.log('My name is: ' + this.name);
    }
});
```

[https://hay.github.io/stapes/#m-general](https://hay.github.io/stapes/#m-general)

**Comment by jerstew** [comment]
Still not updated? Confused me at first and is probably confusing a lot of people since it's the main/only example of how to set up your modules.

**Comment by hay** [comment]
You're right. This has been fixed now.
