### ISSUE TITLE
Subclass does not copy extend static methods

### ISSUE THREAD

**Issue by foxx** [hay/stapes#61]
It would seem that if you `extend` a class then `subclass` it, the static method which you added with `extend` do not appear;

```
    var cls = Stapes.subclass({

    });

    cls.extend({
      hello: function() {
        return 'world';
      }
    });

    var cls2 = cls.subclass({

    })

    var a = cls2();
    console.log(a.hello());
```

```
     TypeError: Object function constructor() {
                // Be kind to people forgetting new
                if (!(this instanceof constructor)) {
                    throw new Error("Please use 'new' when initializing Stapes classes");
                }

                // If this class has events add a GUID as well
                if (this.on) {
                    _.addGuid( this, true );
                }

                realConstructor.apply(this, arguments);
            } has no method 'hello'
```

**Comment by foxx** [comment]
Think I've managed to fix this, just finishing up the unit tests, PR coming shortly

**Comment by foxx** [comment]
This should now be safe for merge.

Unit tests passed on the following browsers;

* Chrome latest on Windows 7
* Firefox latest
* Android emulator 4.4
* Safari 8.0 on Yosemite
* iPhone simulator 8.2 on Yosemite
* IE 11 on Windows 8.1
* IE 10 on Windows 7
* IE 9 on Windows 7

**Comment by foxx** [comment]
PR sent - #63

**Comment by hay** [comment]
Thanks for the PR and bug, but this is intended behaviour. Static methods / properties should only appear on the instance, not on every child. If you want that, you should use `proto` instead of `extend`.
