### ISSUE TITLE
Automated testing and local dev

### ISSUE THREAD

**Issue by foxx** [hay/stapes#62]
There is a lot of pipework missing that makes project contribution difficult. I'm going to send a PR with the following fixes;

* Travis CI integration
* Automated browser testing with BrowserStack
* Vagrant support

For now I'll configure each service on my own personal open source account, and then transfer ownership to you once the PR is merged (perhaps we can coordinate this on IRC/Skype, should only take 5-10 minutes). I'm foxx@freenode and cal.leeming@Skype.

I'm working on this now and will have a PR ready within the next few hours, if you have some spare time today to get this merged that'd be really helpful.

**Comment by foxx** [comment]
PR sent, see #64

**Comment by hay** [comment]
See comment on #64.
