### ISSUE TITLE
Website navigation breaks on small screen

### ISSUE THREAD

**Issue by asarode** [hay/stapes#67]
Hey, cool project. I noticed that documentation site's nav menu is broken on smaller screen. 
<img width="394" alt="screen shot 2015-08-19 at 1 55 08 pm" src="https://cloud.githubusercontent.com/assets/4860899/9366044/948bc5e0-467a-11e5-875d-24f769b01764.png">

**Comment by hay** [comment]
Thanks, this should be fixed now!
