### ISSUE TITLE
Plugin Framework for Stapes

### ISSUE THREAD

**Issue by Asimovtech** [hay/stapes#68]
First of all, hats off to you guys, I moved my jquery project in 3 days flat, I love the flexibility that Stapes gives me, and how easily it gets out of the way.

To me, Stapes seems as powerful as jquery, so I really feel that a plugin framework would do wonders for Stapes. 

here's how I use stapes

`myapp.Stapes` contains all Stapes objects

`myapp` itself contains instantiated Stapes objects. So for example, `myapp.conf` is an instantiated `myapp.Stapes.Config` object.

Maybe we can use this pattern for the plugin framework?

**Comment by hay** [comment]
Hey @Asimovtech, great that you're liking Stapes! 

I'm not quite sure what you mean by a 'plugin framework'. Stapes already has a jQuery-like [plugin structure](http://hay.github.io/stapes/#m-plugins) that you can use to extend the functionality. E.g:

    Stapes.extend({
        // Sets an DOM element for views
        "setElement" : function(el) {
            this.el = el;
            this.$el = $(el); // jQuery or Zepto reference
        }
    });

    var Module = Stapes.subclass();
    var module = new Module();

    module.setElement( document.getElementById("app") );

    console.log( module.el ); // "#app" DOM element
    console.log( module.$el ); // jQuery or Zepto element

**Comment by Asimovtech** [comment]
My bad, actually I was talking about a widget framework on top of Stapes, I found Stapes UI but it seems to lack the simplicity of Stapes.

For now I have a simple framework built for my code. It uses Mustache as a template engine, 

Each template defines the UI of a widget 
I use `<style scoped>` tag to style the widget, the scoped attribute helps keeps the style local to the widget i'm creating
The Stapes object uses the template file in the constructor to create the widget, and functions/events etc. flow from there.

I'm looking for a way to map custom HTML tags to Stapes objects. Once this is done, I should have a minimal widget framework ready.

Hope I make some sense this time :)

**Comment by hay** [comment]
Sure, seems like a nice idea! I could imagine you could also look at a couple of 'one thing well' libraries like Vue.js or Rivets.js that deal with DOM binding, one thing Stapes specifically *does not* do :)
